name: kemon
description: "A new Flutter project."
publish_to: "none"
version: 0.0.1+2

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  collection: ^1.18.0
  either_dart: ^1.0.0
  equatable: ^2.0.5
  expandable: ^5.0.1
  firebase_core: ^2.27.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.4
  flutter_facebook_auth: ^7.0.1
  flutter_keyboard_visibility: ^6.0.0
  flutter_native_splash: ^2.4.0
  flutter_rating_bar: ^4.0.1
  flutter_staggered_grid_view: ^0.7.0
  font_awesome_flutter: ^10.7.0
  get_it: ^7.6.7
  go_router: ^13.2.0
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  html: ^0.15.4
  http: ^1.2.1
  hydrated_bloc: ^9.1.4
  image_picker: ^1.1.1
  in_app_update: ^4.2.3
  internet_connection_checker: ^1.0.0+1
  intl: ^0.19.0
  maps_launcher: ^2.2.1
  package_info_plus: ^8.0.0
  path_provider: ^2.1.2
  pinput: ^5.0.0
  sign_in_with_apple: ^6.1.1
  url_launcher: ^6.3.0

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/logo/
