name: kemon
description: "A new Flutter project."
version: 0.5.1+51
publish_to: none

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  collection: ^1.18.0
  device_info_plus: ^11.1.1
  dots_indicator: ^3.0.0
  either_dart: ^1.0.0
  equatable: ^2.0.5
  expandable: ^5.0.1
  firebase_analytics: ^11.4.0
  firebase_core: ^3.8.0
  firebase_crashlytics: ^4.3.1
  firebase_messaging: ^15.1.5
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.4
  flutter_facebook_auth: ^7.1.1
  flutter_keyboard_visibility: ^6.0.0
  flutter_local_notifications: ^18.0.1
  flutter_native_splash: ^2.4.0
  flutter_rating_bar: ^4.0.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.16
  flutter_timer_countdown: ^1.0.7
  flutter_typeahead: ^5.2.0
  flutter_web_plugins:
    sdk: flutter
  flutter_widget_from_html: ^0.15.1
  font_awesome_flutter: ^10.8.0
  get_it: ^8.0.1
  go_router: ^14.3.0
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.2
  html: ^0.15.4
  http: ^1.2.2
  hydrated_bloc: ^9.1.4
  image_picker: ^1.1.1
  in_app_update: ^4.2.3
  internet_connection_checker: ^1.0.0+1
  intl: ^0.19.0
  maps_launcher:
    git:
      url: https://github.com/pikaju/flutter-maps-launcher.git
      ref: master
  package_info_plus: ^8.0.0
  path_provider: ^2.1.2
  photo_view: ^0.15.0
  pinput: ^5.0.0
  readmore: ^3.0.0
  recase: ^4.1.0
  sa3_liquid: ^1.0.1
  share_plus: ^10.1.2
  simple_animations: ^5.1.0
  smooth_highlight: ^0.1.2
  url_launcher: ^6.3.0

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_driver:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  patrol: ^3.13.2

flutter:
  uses-material-design: true
  assets:
    - api/
    - images/
    - images/logo/
    - images/medal/
    - changelog.json

patrol:
  app_name: kemon
  android:
    package_name: bd.com.kemon
