// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqubdSur5tsfI73deWH8ZuBJ5pc-1QgGU',
    appId: '1:974762887289:android:5b5c116c3676d31014eca8',
    messagingSenderId: '974762887289',
    projectId: 'kemon-public',
    storageBucket: 'kemon-public.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQx6OKI3psO1VfhdFiRWwilka35W5ff8s',
    appId: '1:974762887289:ios:c72ae106dd8c27a714eca8',
    messagingSenderId: '974762887289',
    projectId: 'kemon-public',
    storageBucket: 'kemon-public.firebasestorage.app',
    androidClientId: '974762887289-qj66pq1vscknvo7ol76dbtqtp1hum9c4.apps.googleusercontent.com',
    iosClientId: '974762887289-5scbsso7cgee6uohdrt34cegq5uss5q0.apps.googleusercontent.com',
    iosBundleId: 'com.kemon.public',
  );

}